services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    image: mariadb
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      -
    networks:
      - inception
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
  nginx:
    container_name: nginx
    env_file:
      - .env
  ### BONUS (TODO) ###

########## DOCKER SECRETS ##########
secrets:
  db_admin_pass:
    file: db_admin_pass.txt
  db_user_pass:
    file: db_user_pass.txt
  ftp_password:
    file: ftp_password.txt
  wp_admin_pass:
    file: wp_admin_pass.txt
  wp_user_pass:
    file: wp_user_pass.txt