services:
    nginx:
        container_name: nginx
        env_file:
            - .env
        build:
            context: ./requirements/nginx
        image: nginx:inception
        depends_on:
            - wordpress
        networks:
            - inception
        volumes:
            - wordpress_data:/var/www/wordpress
            - adminer_data:/var/www/adminer
        ports:
            - 443:443
        restart: unless-stopped

    mariadb:
        container_name: mariadb
        env_file:
            - .env
        build:
            context: ./requirements/mariadb
            args:
                DEBIAN_VERSION: ${DEBIAN_VERSION}
        image: mariadb:inception
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "--silent"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - wordpress_db:/var/lib/mysql
        networks:
            - inception
        expose:
            - 3306
        restart: unless-stopped

    wordpress:
        container_name: wordpress
        env_file:
            - .env
        build:
            context: ./requirements/wordpress
        image: wordpress:inception
        depends_on:
            mariadb:
                condition: service_healthy
        volumes:
            - wordpress_data:/var/www/wordpress
        networks:
            - inception
        expose:
            - 9000
        restart: unless-stopped
    
    # BONUS PART
    static:
        container_name: static
        env_file:
            - .env
        build:
            context: ./requirements/bonus/static
        image: static:inception
        networks:
            - inception
        expose:
            - 3000
        ports:
         - 3000:3000 
    redis:
        container_name: redis
        image: redis:inception
        env_file:
            - .env
        build: 
            context: ./requirements/bonus/redis
        restart: unless-stopped
        networks:
            - inception
        expose:
            - 6379
    adminer:
        container_name: adminer
        image: adminer:inception
        env_file:
            - .env
        build: 
            context: ./requirements/bonus/adminer
        restart: unless-stopped
        networks:
            - inception
        volumes:
            - adminer_data:/var/www/adminer
        expose:
            - 9000
    ftp:
        container_name: ftp
        env_file:
            - .env
        build:
            context: ./requirements/bonus/ftp
        image: ftp:inception
        volumes:
            - wordpress_data:/var/www/wordpress
        networks:
            - inception
        ports:
            - "21:21"
            - "20:20"
            - "21100-21110:21100-21110"
    ngrok:
        container_name: ngrok
        build:
            context: ./requirements/bonus/ngrok
        env_file:
         - .env
        image: ngrok:inception
        environment:
            - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
            - NGROK_PORT=3000 
        networks:
            - inception
        depends_on:
            - static
        restart: unless-stopped


networks:
    inception:
        driver: bridge

volumes:
    wordpress_db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/wordpress_db

    wordpress_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/wordpress
    adminer_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/adminer
